# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 1208)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(50, 50, 531, 951))
        self.tabWidget.setObjectName("tabWidget")
        self.Ciphertext = QtWidgets.QWidget()
        self.Ciphertext.setObjectName("Ciphertext")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.Ciphertext)
        self.buttonBox.setGeometry(QtCore.QRect(30, 20, 111, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(self.Ciphertext)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 200, 99, 705))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.f_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.f_interrupter.setObjectName("f_interrupter")
        self.verticalLayout_2.addWidget(self.f_interrupter)
        self.u_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.u_interrupter.setObjectName("u_interrupter")
        self.verticalLayout_2.addWidget(self.u_interrupter)
        self.th_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.th_interrupter.setObjectName("th_interrupter")
        self.verticalLayout_2.addWidget(self.th_interrupter)
        self.u_interrupter_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.u_interrupter_2.setObjectName("u_interrupter_2")
        self.verticalLayout_2.addWidget(self.u_interrupter_2)
        self.r_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.r_interrupter.setObjectName("r_interrupter")
        self.verticalLayout_2.addWidget(self.r_interrupter)
        self.c_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.c_interrupter.setObjectName("c_interrupter")
        self.verticalLayout_2.addWidget(self.c_interrupter)
        self.g_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.g_interrupter.setObjectName("g_interrupter")
        self.verticalLayout_2.addWidget(self.g_interrupter)
        self.w_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.w_interrupter.setObjectName("w_interrupter")
        self.verticalLayout_2.addWidget(self.w_interrupter)
        self.h_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.h_interrupter.setObjectName("h_interrupter")
        self.verticalLayout_2.addWidget(self.h_interrupter)
        self.n_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.n_interrupter.setObjectName("n_interrupter")
        self.verticalLayout_2.addWidget(self.n_interrupter)
        self.f_interrupter_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.f_interrupter_2.setObjectName("f_interrupter_2")
        self.verticalLayout_2.addWidget(self.f_interrupter_2)
        self.j_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.j_interrupter.setObjectName("j_interrupter")
        self.verticalLayout_2.addWidget(self.j_interrupter)
        self.eo_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.eo_interrupter.setObjectName("eo_interrupter")
        self.verticalLayout_2.addWidget(self.eo_interrupter)
        self.p_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.p_interrupter.setObjectName("p_interrupter")
        self.verticalLayout_2.addWidget(self.p_interrupter)
        self.x_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.x_interrupter.setObjectName("x_interrupter")
        self.verticalLayout_2.addWidget(self.x_interrupter)
        self.s_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.s_interrupter.setObjectName("s_interrupter")
        self.verticalLayout_2.addWidget(self.s_interrupter)
        self.t_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.t_interrupter.setObjectName("t_interrupter")
        self.verticalLayout_2.addWidget(self.t_interrupter)
        self.b_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.b_interrupter.setObjectName("b_interrupter")
        self.verticalLayout_2.addWidget(self.b_interrupter)
        self.e_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.e_interrupter.setObjectName("e_interrupter")
        self.verticalLayout_2.addWidget(self.e_interrupter)
        self.m_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.m_interrupter.setObjectName("m_interrupter")
        self.verticalLayout_2.addWidget(self.m_interrupter)
        self.l_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.l_interrupter.setObjectName("l_interrupter")
        self.verticalLayout_2.addWidget(self.l_interrupter)
        self.ing_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.ing_interrupter.setObjectName("ing_interrupter")
        self.verticalLayout_2.addWidget(self.ing_interrupter)
        self.oe_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.oe_interrupter.setObjectName("oe_interrupter")
        self.verticalLayout_2.addWidget(self.oe_interrupter)
        self.d_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.d_interrupter.setObjectName("d_interrupter")
        self.verticalLayout_2.addWidget(self.d_interrupter)
        self.a_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.a_interrupter.setObjectName("a_interrupter")
        self.verticalLayout_2.addWidget(self.a_interrupter)
        self.ae_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.ae_interrupter.setObjectName("ae_interrupter")
        self.verticalLayout_2.addWidget(self.ae_interrupter)
        self.y_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_interrupter.setObjectName("y_interrupter")
        self.verticalLayout_2.addWidget(self.y_interrupter)
        self.io_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.io_interrupter.setObjectName("io_interrupter")
        self.verticalLayout_2.addWidget(self.io_interrupter)
        self.ea_interrupter = QtWidgets.QRadioButton(self.layoutWidget)
        self.ea_interrupter.setObjectName("ea_interrupter")
        self.verticalLayout_2.addWidget(self.ea_interrupter)
        self.widget = QtWidgets.QWidget(self.Ciphertext)
        self.widget.setGeometry(QtCore.QRect(380, 20, 99, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.forward_gematria = QtWidgets.QRadioButton(self.widget)
        self.forward_gematria.setObjectName("forward_gematria")
        self.verticalLayout.addWidget(self.forward_gematria)
        self.reverse_gematria = QtWidgets.QRadioButton(self.widget)
        self.reverse_gematria.setObjectName("reverse_gematria")
        self.verticalLayout.addWidget(self.reverse_gematria)
        self.all_forward_gematria = QtWidgets.QRadioButton(self.widget)
        self.all_forward_gematria.setObjectName("all_forward_gematria")
        self.verticalLayout.addWidget(self.all_forward_gematria)
        self.all_reverse_gematria = QtWidgets.QRadioButton(self.widget)
        self.all_reverse_gematria.setObjectName("all_reverse_gematria")
        self.verticalLayout.addWidget(self.all_reverse_gematria)
        self.all_gematria = QtWidgets.QRadioButton(self.widget)
        self.all_gematria.setObjectName("all_gematria")
        self.verticalLayout.addWidget(self.all_gematria)
        self.tabWidget.addTab(self.Ciphertext, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Interrupters"))
        self.radioButton.setText(_translate("Dialog", "All"))
        self.f_interrupter.setText(_translate("Dialog", "ᚠ"))
        self.u_interrupter.setText(_translate("Dialog", "ᚢ"))
        self.th_interrupter.setText(_translate("Dialog", "ᚦ"))
        self.u_interrupter_2.setText(_translate("Dialog", "ᚩ"))
        self.r_interrupter.setText(_translate("Dialog", "ᚱ"))
        self.c_interrupter.setText(_translate("Dialog", "ᚳ"))
        self.g_interrupter.setText(_translate("Dialog", "ᚷ"))
        self.w_interrupter.setText(_translate("Dialog", "ᚹ"))
        self.h_interrupter.setText(_translate("Dialog", "ᚻ"))
        self.n_interrupter.setText(_translate("Dialog", "ᚾ"))
        self.f_interrupter_2.setText(_translate("Dialog", "ᛁ"))
        self.j_interrupter.setText(_translate("Dialog", "ᛂ"))
        self.eo_interrupter.setText(_translate("Dialog", "ᛇ"))
        self.p_interrupter.setText(_translate("Dialog", "ᛈ"))
        self.x_interrupter.setText(_translate("Dialog", "ᛉ"))
        self.s_interrupter.setText(_translate("Dialog", "ᛋ"))
        self.t_interrupter.setText(_translate("Dialog", "ᛏ"))
        self.b_interrupter.setText(_translate("Dialog", "ᛒ"))
        self.e_interrupter.setText(_translate("Dialog", "ᛖ"))
        self.m_interrupter.setText(_translate("Dialog", "ᛗ"))
        self.l_interrupter.setText(_translate("Dialog", "ᛚ"))
        self.ing_interrupter.setText(_translate("Dialog", "ᛝ"))
        self.oe_interrupter.setText(_translate("Dialog", "ᛟ"))
        self.d_interrupter.setText(_translate("Dialog", "ᛞ"))
        self.a_interrupter.setText(_translate("Dialog", "ᚪ"))
        self.ae_interrupter.setText(_translate("Dialog", "ᚫ"))
        self.y_interrupter.setText(_translate("Dialog", "ᚣ"))
        self.io_interrupter.setText(_translate("Dialog", "ᛡ"))
        self.ea_interrupter.setText(_translate("Dialog", "ᛠ"))
        self.label.setText(_translate("Dialog", "Gematria Rotations"))
        self.forward_gematria.setText(_translate("Dialog", "Forward"))
        self.reverse_gematria.setText(_translate("Dialog", "Reverse"))
        self.all_forward_gematria.setText(_translate("Dialog", "All Forward"))
        self.all_reverse_gematria.setText(_translate("Dialog", "All Reverse"))
        self.all_gematria.setText(_translate("Dialog", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ciphertext), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Cipher text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
