# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainView(object):
    def setupUi(self, mainView):
        mainView.setObjectName("mainView")
        mainView.resize(400, 848)
        self.centralwidget = QtWidgets.QWidget(mainView)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 381, 791))
        self.tabWidget.setObjectName("tabWidget")
        self.Ciphertext_2 = QtWidgets.QWidget()
        self.Ciphertext_2.setObjectName("Ciphertext_2")
        self.label = QtWidgets.QLabel(self.Ciphertext_2)
        self.label.setGeometry(QtCore.QRect(10, 250, 271, 16))
        self.label.setObjectName("label")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.Ciphertext_2)
        self.buttonBox_2.setGeometry(QtCore.QRect(75, 22, 75, 52))
        self.buttonBox_2.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.Ciphertext_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 270, 256, 31))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.Ciphertext_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lpSectionBox = QtWidgets.QGroupBox(self.tab_3)
        self.lpSectionBox.setGeometry(QtCore.QRect(20, 30, 91, 311))
        self.lpSectionBox.setFlat(False)
        self.lpSectionBox.setCheckable(False)
        self.lpSectionBox.setObjectName("lpSectionBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lpSectionBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lp_section1 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section1.setObjectName("lp_section1")
        self.verticalLayout_2.addWidget(self.lp_section1)
        self.lp_section2 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section2.setObjectName("lp_section2")
        self.verticalLayout_2.addWidget(self.lp_section2)
        self.lp_section3 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section3.setObjectName("lp_section3")
        self.verticalLayout_2.addWidget(self.lp_section3)
        self.lp_section4 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section4.setObjectName("lp_section4")
        self.verticalLayout_2.addWidget(self.lp_section4)
        self.lp_section5 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section5.setObjectName("lp_section5")
        self.verticalLayout_2.addWidget(self.lp_section5)
        self.lp_section6 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section6.setObjectName("lp_section6")
        self.verticalLayout_2.addWidget(self.lp_section6)
        self.lp_section7 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section7.setObjectName("lp_section7")
        self.verticalLayout_2.addWidget(self.lp_section7)
        self.lp_section8 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section8.setObjectName("lp_section8")
        self.verticalLayout_2.addWidget(self.lp_section8)
        self.lp_section9 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section9.setObjectName("lp_section9")
        self.verticalLayout_2.addWidget(self.lp_section9)
        self.lp_section10 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section10.setObjectName("lp_section10")
        self.verticalLayout_2.addWidget(self.lp_section10)
        self.lp_section11 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section11.setObjectName("lp_section11")
        self.verticalLayout_2.addWidget(self.lp_section11)
        self.lp_section12 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section12.setObjectName("lp_section12")
        self.verticalLayout_2.addWidget(self.lp_section12)
        self.lp_section13 = QtWidgets.QCheckBox(self.lpSectionBox)
        self.lp_section13.setObjectName("lp_section13")
        self.verticalLayout_2.addWidget(self.lp_section13)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 30, 112, 119))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_4.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_4.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_4.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_4.addWidget(self.checkBox_21)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(20, 350, 341, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 10, 301, 341))
        self.textEdit_2.setObjectName("textEdit_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 91, 717))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_interrupters = QtWidgets.QCheckBox(self.groupBox_2)
        self.all_interrupters.setObjectName("all_interrupters")
        self.verticalLayout.addWidget(self.all_interrupters)
        self.f_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.f_interrupter.setObjectName("f_interrupter")
        self.verticalLayout.addWidget(self.f_interrupter)
        self.u_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.u_interrupter.setObjectName("u_interrupter")
        self.verticalLayout.addWidget(self.u_interrupter)
        self.th_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.th_interrupter.setObjectName("th_interrupter")
        self.verticalLayout.addWidget(self.th_interrupter)
        self.o_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.o_interrupter.setObjectName("o_interrupter")
        self.verticalLayout.addWidget(self.o_interrupter)
        self.r_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.r_interrupter.setObjectName("r_interrupter")
        self.verticalLayout.addWidget(self.r_interrupter)
        self.c_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.c_interrupter.setObjectName("c_interrupter")
        self.verticalLayout.addWidget(self.c_interrupter)
        self.g_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.g_interrupter.setObjectName("g_interrupter")
        self.verticalLayout.addWidget(self.g_interrupter)
        self.w_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.w_interrupter.setObjectName("w_interrupter")
        self.verticalLayout.addWidget(self.w_interrupter)
        self.h_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.h_interrupter.setObjectName("h_interrupter")
        self.verticalLayout.addWidget(self.h_interrupter)
        self.n_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.n_interrupter.setObjectName("n_interrupter")
        self.verticalLayout.addWidget(self.n_interrupter)
        self.i_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.i_interrupter.setObjectName("i_interrupter")
        self.verticalLayout.addWidget(self.i_interrupter)
        self.j_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.j_interrupter.setObjectName("j_interrupter")
        self.verticalLayout.addWidget(self.j_interrupter)
        self.eo_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.eo_interrupter.setObjectName("eo_interrupter")
        self.verticalLayout.addWidget(self.eo_interrupter)
        self.p_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.p_interrupter.setObjectName("p_interrupter")
        self.verticalLayout.addWidget(self.p_interrupter)
        self.x_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.x_interrupter.setObjectName("x_interrupter")
        self.verticalLayout.addWidget(self.x_interrupter)
        self.s_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.s_interrupter.setObjectName("s_interrupter")
        self.verticalLayout.addWidget(self.s_interrupter)
        self.t_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.t_interrupter.setObjectName("t_interrupter")
        self.verticalLayout.addWidget(self.t_interrupter)
        self.b_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.b_interrupter.setObjectName("b_interrupter")
        self.verticalLayout.addWidget(self.b_interrupter)
        self.e_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.e_interrupter.setObjectName("e_interrupter")
        self.verticalLayout.addWidget(self.e_interrupter)
        self.m_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_interrupter.setObjectName("m_interrupter")
        self.verticalLayout.addWidget(self.m_interrupter)
        self.l_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.l_interrupter.setObjectName("l_interrupter")
        self.verticalLayout.addWidget(self.l_interrupter)
        self.ing_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.ing_interrupter.setObjectName("ing_interrupter")
        self.verticalLayout.addWidget(self.ing_interrupter)
        self.oe_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.oe_interrupter.setObjectName("oe_interrupter")
        self.verticalLayout.addWidget(self.oe_interrupter)
        self.d_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.d_interrupter.setObjectName("d_interrupter")
        self.verticalLayout.addWidget(self.d_interrupter)
        self.a_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.a_interrupter.setObjectName("a_interrupter")
        self.verticalLayout.addWidget(self.a_interrupter)
        self.ae_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.ae_interrupter.setObjectName("ae_interrupter")
        self.verticalLayout.addWidget(self.ae_interrupter)
        self.y_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.y_interrupter.setObjectName("y_interrupter")
        self.verticalLayout.addWidget(self.y_interrupter)
        self.io_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.io_interrupter.setObjectName("io_interrupter")
        self.verticalLayout.addWidget(self.io_interrupter)
        self.ea_interrupter = QtWidgets.QCheckBox(self.groupBox_2)
        self.ea_interrupter.setObjectName("ea_interrupter")
        self.verticalLayout.addWidget(self.ea_interrupter)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(140, 20, 97, 142))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.forward_gematria = QtWidgets.QCheckBox(self.groupBox_4)
        self.forward_gematria.setObjectName("forward_gematria")
        self.verticalLayout_3.addWidget(self.forward_gematria)
        self.reverse_gematria = QtWidgets.QCheckBox(self.groupBox_4)
        self.reverse_gematria.setObjectName("reverse_gematria")
        self.verticalLayout_3.addWidget(self.reverse_gematria)
        self.all_forward_gematria = QtWidgets.QCheckBox(self.groupBox_4)
        self.all_forward_gematria.setObjectName("all_forward_gematria")
        self.verticalLayout_3.addWidget(self.all_forward_gematria)
        self.all_reverse_gematria = QtWidgets.QCheckBox(self.groupBox_4)
        self.all_reverse_gematria.setObjectName("all_reverse_gematria")
        self.verticalLayout_3.addWidget(self.all_reverse_gematria)
        self.all_gematria = QtWidgets.QCheckBox(self.groupBox_4)
        self.all_gematria.setObjectName("all_gematria")
        self.verticalLayout_3.addWidget(self.all_gematria)
        self.tabWidget.addTab(self.tab, "")
        mainView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        mainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainView)
        self.statusbar.setObjectName("statusbar")
        mainView.setStatusBar(self.statusbar)

        self.retranslateUi(mainView)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainView)

    def retranslateUi(self, mainView):
        _translate = QtCore.QCoreApplication.translate
        mainView.setWindowTitle(_translate("mainView", "MainWindow"))
        self.label.setText(_translate("mainView", "Key Phrase (English or comma seperated list)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ciphertext_2), _translate("mainView", "Tab 1"))
        self.lpSectionBox.setTitle(_translate("mainView", "LP Section"))
        self.lp_section1.setText(_translate("mainView", "Section 1"))
        self.lp_section2.setText(_translate("mainView", "Section 2"))
        self.lp_section3.setText(_translate("mainView", "Section 3"))
        self.lp_section4.setText(_translate("mainView", "Section 4"))
        self.lp_section5.setText(_translate("mainView", "Section 5"))
        self.lp_section6.setText(_translate("mainView", "Section 6"))
        self.lp_section7.setText(_translate("mainView", "Section 7"))
        self.lp_section8.setText(_translate("mainView", "Section 8"))
        self.lp_section9.setText(_translate("mainView", "Section 9"))
        self.lp_section10.setText(_translate("mainView", "Section 10"))
        self.lp_section11.setText(_translate("mainView", "Section 11"))
        self.lp_section12.setText(_translate("mainView", "Section 12"))
        self.lp_section13.setText(_translate("mainView", "Section 13"))
        self.groupBox_3.setTitle(_translate("mainView", "Word Selection"))
        self.checkBox_18.setText(_translate("mainView", "Start Words"))
        self.checkBox_19.setText(_translate("mainView", "End Words"))
        self.checkBox_20.setText(_translate("mainView", "Start and  End"))
        self.checkBox_21.setText(_translate("mainView", "All Words"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainView", "Cipher text"))
        self.groupBox_2.setTitle(_translate("mainView", "Interrupter"))
        self.all_interrupters.setText(_translate("mainView", "All"))
        self.f_interrupter.setText(_translate("mainView", "ᚠ"))
        self.u_interrupter.setText(_translate("mainView", "ᚢ"))
        self.th_interrupter.setText(_translate("mainView", "ᚦ"))
        self.o_interrupter.setText(_translate("mainView", "ᚩ"))
        self.r_interrupter.setText(_translate("mainView", "ᚱ"))
        self.c_interrupter.setText(_translate("mainView", "ᚳ"))
        self.g_interrupter.setText(_translate("mainView", "ᚷ"))
        self.w_interrupter.setText(_translate("mainView", "ᚹ"))
        self.h_interrupter.setText(_translate("mainView", "ᚻ"))
        self.n_interrupter.setText(_translate("mainView", "ᚾ"))
        self.i_interrupter.setText(_translate("mainView", "ᛁ"))
        self.j_interrupter.setText(_translate("mainView", "ᛂ"))
        self.eo_interrupter.setText(_translate("mainView", "ᛇ"))
        self.p_interrupter.setText(_translate("mainView", "ᛈ"))
        self.x_interrupter.setText(_translate("mainView", "ᛉ"))
        self.s_interrupter.setText(_translate("mainView", "ᛋ"))
        self.t_interrupter.setText(_translate("mainView", "ᛏ"))
        self.b_interrupter.setText(_translate("mainView", "ᛒ"))
        self.e_interrupter.setText(_translate("mainView", "ᛖ"))
        self.m_interrupter.setText(_translate("mainView", "ᛗ"))
        self.l_interrupter.setText(_translate("mainView", "ᛚ"))
        self.ing_interrupter.setText(_translate("mainView", "ᛝ"))
        self.oe_interrupter.setText(_translate("mainView", "ᛟ"))
        self.d_interrupter.setText(_translate("mainView", "ᛞ"))
        self.a_interrupter.setText(_translate("mainView", "ᚪ"))
        self.ae_interrupter.setText(_translate("mainView", "ᚫ"))
        self.y_interrupter.setText(_translate("mainView", "ᚣ"))
        self.io_interrupter.setText(_translate("mainView", "ᛡ"))
        self.ea_interrupter.setText(_translate("mainView", "ᛠ"))
        self.groupBox_4.setTitle(_translate("mainView", "Gematria Rotations"))
        self.forward_gematria.setText(_translate("mainView", "Forward"))
        self.reverse_gematria.setText(_translate("mainView", "Reverse"))
        self.all_forward_gematria.setText(_translate("mainView", "All Forward"))
        self.all_reverse_gematria.setText(_translate("mainView", "All Reverse"))
        self.all_gematria.setText(_translate("mainView", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainView", "Page"))
